apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "boatramp-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "boatramp-operator.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "boatramp-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "boatramp-operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "boatramp-operator.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          image: {{ include "boatramp-operator.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - operator
            - run
            {{- with .Values.watchNamespace }}
            - --namespace
            - {{ . | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
